# Generated by Django 5.2.5 on 2025-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('specialite', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Filiere',
            new_name='Classe',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='filiere',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='filiere',
            new_name='classe',
        ),
    ]
